version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "8443:8443"
    volumes:
      - ./src/html:/var/www/html
      - ./src/config/nginx.conf:/etc/nginx/nginx.conf
      - ./src/config/default.conf:/etc/nginx/sites-available/default
      - ./src/ssl:/etc/nginx/ssl
    restart: unless-stopped